### ISSUE TITLE
post actions on installations should be optional

### ISSUE THREAD

**Issue by smiklosovic** [arquillian/arquillian-spacelift-gradle-plugin#11]
Right now, it is common pattern to build something by Maven in installation's post actions closure but even the project I am building with Maven does not change at all over script invocations, it is constantly being built again and again.

I would add there some precondition which would trigger post actions only if that closure returns true.

This should hold for any installation, not only Maven based.

**Comment by TadeasKriz** [comment]
Solved now?

**Comment by kpiwko** [comment]
Well, now there is isInstalled {}. If this returns true, Installation just registers tools, postActions are thus executed only once.

**Comment by smiklosovic** [comment]
That solution is sufficient for me. If I understand it correctly, while taking Maven based installation into consideration, I would have to make a check if a project which is about to be built is already present in the repository.

**Comment by kpiwko** [comment]
Exactly. Closing for now.
