### ISSUE TITLE
I can not add env properties to CommandBuilder

### ISSUE THREAD

**Issue by smiklosovic** [arquillian/arquillian-spacelift-gradle-plugin#27]
@kpiwko 

When I was specifying some tool and I returned CommandTool, I could set environment properties by calling addEnvironment() on it.

Now I have to return CommandBuilder from command closure but I can not pass there any environment properties.

In this particular case, I need to set ANDROID_HOME and ANDROID_SDK_HOME environment properties to AndroidInstallation hence I need to set this.environment property in AndroidTool constructor, however I do not know how to pass it there.

Currently there is not any workaround known for me.

I would like to know, what was the motivation behind returning only CommandBuilder from command closures. It seems like you lost the possibility to pass there environment properties to it.

**Comment by kpiwko** [comment]
Closing, please read DSL description in readme file, tool has more closures than just command.
