### ISSUE TITLE
Spacelift wraps list in dataProvider block into another list

### ISSUE THREAD

**Issue by okiss** [arquillian/arquillian-spacelift-gradle-plugin#32]
Because of this, blocks that use dataProvider are executed only once, using the entire list. Instead, they should be executed once for each item in the provided list.

flatten() can be used in dataProvider to work around this issue

**Comment by TadeasKriz** [comment]
I think in github.com/aerogear/aerogear-unifiedpush-server-integration-tests/build.gradle I had to use a workaround for similar issue. Please try if it suits you.

**Comment by kpiwko** [comment]
@okiss, @TadeasKriz anybody will to provide unit test for the plugin? This is a functionality that should be tested with each internal change - should go here: https://github.com/arquillian/arquillian-spacelift-gradle-plugin/blob/master/src/test/groovy/org/arquillian/spacelift/gradle/DefaultTestExecutionLifecycleTest.groovy

**Comment by kpiwko** [comment]
Also, might be related to #25

**Comment by okiss** [comment]
@kpiwko I'll try to make the test

**Comment by okiss** [comment]
I opened a pull request with the tests: https://github.com/arquillian/arquillian-spacelift-gradle-plugin/pull/35, but the issue appears to be already fixed in alpha-7

**Comment by kpiwko** [comment]
Resolved, fixed in Alpha-7.
